### ISSUE TITLE
git的最新项目编译错误

### ISSUE THREAD

**Issue by li-keli** [SunLiner/Floral#1]
> 我是刚开始学swift的菜鸟了，请教一个编译错误的问题，也许很常见，但是目前的我还是不懂的；
> PS，已经百度过，并没有找到合适的答案。

![问题截图](http://images2015.cnblogs.com/blog/624228/201606/624228-20160611094413527-308582389.png)

**Comment by li-keli** [comment]
> 还有下面两个文件，标红报错：

![image](https://cloud.githubusercontent.com/assets/9330061/15982626/f1cca5ca-2fbe-11e6-833d-c03a7a9a0c32.png)

**Comment by SunLiner** [comment]
打开Floral.xcworkspace, 而不是Floral.xcodeproj
