### ISSUE TITLE
保存登录状态，少加了synchronize

### ISSUE THREAD

**Issue by huangxinyu1213** [SunLiner/Floral#2]

**Comment by SunLiner** [comment]
iOS7之前需要自动同步.现在已经不用了, 他会自动同步的, 不信可以自己试试哦...

**Comment by huangxinyu1213** [comment]
哦哦，还不知道，谢谢。另外NSUserDefaults.standardUserDefaults().objectForKey(LoginStatus) as? Bool，这个不用boolForKey，取出来的也是Bool么？

**Comment by SunLiner** [comment]
不用的话, 取出来的应该是AnyObject, 但是这儿必须指定类型的, 因为你有可能取出来的是nil, 所以必须加上可选类型
