### ISSUE TITLE
高手 代码写的蛮好

### ISSUE THREAD

**Issue by jj89757hhb** [SunLiner/Floral#3]

**Comment by SunLiner** [comment]
O(∩_∩)O谢谢夸奖. 我也是小菜一枚.希望代码能给你带来一些帮助.

**Comment by jj89757hhb** [comment]
你是这个app的开发者吗

**Comment by SunLiner** [comment]
这个真不是.我只是觉得这个APP做的不错, 就用它来给swift练手的.

**Comment by jj89757hhb** [comment]
好吧  ，咋接口你都知道啦

**Comment by SunLiner** [comment]
可以用青花瓷抓包的.很简单的.网上很多教程.

**Comment by jj89757hhb** [comment]
恩 那软件体验过 

请问一下你那里有几个外部的字体，程序中有加载吗？

**Comment by SunLiner** [comment]
有的. 你可以用字体名全文搜索一下.用法很简单的.

**Comment by jj89757hhb** [comment]
恩 明白啦 
   cell.textLabel?.font = UIFont.init(name: "CODE LIGHT", size: 14)
