### ISSUE TITLE
进入商城闪退

### ISSUE THREAD

**Issue by narakai** [SunLiner/Floral#9]
2016-07-28 11:20:53.959 Floral[1894:1271963] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[<Floral.ADS 0x145ea99f0> setNilValueForKey]: could not set nil as the value for the key fnOrder.'
**\* First throw call stack:
(0x18265edb0 0x181cc3f80 0x18265ecf8 0x182ffa16c 0x182f6b6e4 0x182ffa39c 0x10015aad4 0x10015abf4 0x100131ce0 0x10061dcac 0x10061c9ac 0x1005dad18 0x1820a94bc 0x1820a947c 0x1820aeb84 0x182614d50 0x182612bb8 0x18253cc50 0x183e24088 0x187826088 0x10016111c 0x1820da8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
Signal: SIGABRT (signal SIGABRT)

init(dict:[String : AnyObject]) {
        super.init()
        setValuesForKeysWithDictionary(dict)
    }

进入商城这里报错了，麻烦看下呢

**Comment by narakai** [comment]
ps: 测试机 iphone 6s

**Comment by SunLiner** [comment]
已经修复， 请下载最新代码
